// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATLqHoaZvjau1NirBeQPPn6dkvphac-GY',
    appId: '1:760396672882:web:d224ead5532b1f5cfe77eb',
    messagingSenderId: '760396672882',
    projectId: 'learning-management-syst-16b9f',
    authDomain: 'learning-management-syst-16b9f.firebaseapp.com',
    storageBucket: 'learning-management-syst-16b9f.firebasestorage.app',
    measurementId: 'G-4P9R86TW4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVB97DJVrGhJNf41nAb6FSNRtTxObAaxg',
    appId: '1:760396672882:android:8b11cc8f0ed6c3f2fe77eb',
    messagingSenderId: '760396672882',
    projectId: 'learning-management-syst-16b9f',
    storageBucket: 'learning-management-syst-16b9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA14Nu4LtadOwlvb1BWeBhETx9y9FvYnfo',
    appId: '1:760396672882:ios:e692090ba50edadafe77eb',
    messagingSenderId: '760396672882',
    projectId: 'learning-management-syst-16b9f',
    storageBucket: 'learning-management-syst-16b9f.firebasestorage.app',
    iosBundleId: 'com.example.learningManagementSystem',
  );
}
